---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "imagepullsecret-patcher.fullname" . }}
  labels:
    {{- include "imagepullsecret-patcher.labels" . | nindent 4 }}
rules:
  {{- (.Files.Get "_generated/rbac/role.yaml" | fromYaml).rules | toYaml | nindent 2}}
