---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "imagepullsecret-patcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imagepullsecret-patcher.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "imagepullsecret-patcher.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "imagepullsecret-patcher.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
